name: Infer Report

on:
  push:
    branches:
      - master

jobs:
  infer:
    name: Static analysis (Infer)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Install Infer
        env:
          VERSION: "1.0.0"
        run: |
          wget "https://github.com/facebook/infer/releases/download/v${VERSION}/infer-linux64-v${VERSION}.tar.xz"
          tar xJf "infer-linux64-v${VERSION}.tar.xz"
          rm -rf "infer-linux64-v${VERSION}.tar.xz"
      - name: Run Infer
        env:
          VERSION: "1.0.0"
        run: |
          ./infer-linux64-v${VERSION}/bin/infer --version
          ./infer-linux64-v${VERSION}/bin/infer -- mvn -DskipTests=true clean package
          ls -al ./infer-out/
      - name: push to github infer-out branch
        run: |
          git config --global user.name "jiangxincode"
          git config --global user.email "jiangxinnju@163.com"
          git clone https://github.com/jiangxincode/ApkToolBoxGUI.git -b infer-out infer-out-git
          cp ./infer-out/report.txt ./infer-out-git/
          cd ./infer-out-git
          echo `date` > current.date
          git add --all
          git commit -m "update infer-out"
          git push -f https://jiangxincode:${{secrets.GITHUB_TOKEN}}@github.com/jiangxincode/ApkToolBoxGUI.git infer-out:infer-out